### PR TITLE
Enable Horizontal Scroll

### PR DESCRIPTION
**Pull request by tangorri**
as discussed here https://github.com/aminer-looker/angular-gridster/commit/bbc0d70055638dfbbff45b76540d461f0bffc3e6

### CODE REVIEW

**Comment by aminer-looker** [comment]
Where there actually changes to the CSS?  I'm seeing the entire file as being changed, but I'm guessing that's just because you re-built it.

**Comment by aminer-looker** [comment]
Looks good!  Would you mind squashing your branch and resubmitting?  It would be nice to have a single commit which encapsulates your full change.

**Comment by tangorri** [comment]
iep, I clean it asap and resubmit, with options added. First time I do a 'branch squash' so let me learn how to do it well :) and sorry for the last commit I'll remove it.

**Comment by aminer-looker** [comment]
@tangorri — The easiest way is to create a new branch from `master`, and then use `git merge --squash <your other branch>`.  This should result in a bunch of uncommitted changes in your working directory.  You can then `git add -A` and `git commit` as usual.

**Comment by tangorri** [comment]
thanks for the tip ! I didn't know about rebase/squash etc. I've read some docs.
That's said, I submitted #3, tell me it's alright :)

**Pull request closed without merging**
